# Generated by Django 4.0.4 on 2022-05-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Produto',
        ),
    ]
