# Generated by Django 4.0.4 on 2022-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_rename_post_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('raca', models.CharField(max_length=200)),
                ('dono', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
