# Generated by Django 4.0.4 on 2022-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_animais_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='tipo',
            field=models.CharField(choices=[('', 'Escolha..'), ('1', 'Gato'), ('2', 'Cachorro')], max_length=1),
        ),
    ]
